version: '3.8'  # Optional, kann je nach Docker Compose Version variieren

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: soluna-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file:
      - .env
    environment:
      COC_EMAIL: "alperen.adatepe1905@gmail.com"
      COC_PASSWORD: "itiFGQnr7H%Dov@1zR"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nextjs_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge
